version: '3'
services:
  
  gateway:
    container_name: gateway-proxy
    build:
      context: ./gateway-proxy/
      dockerfile: Dockerfile
    ports:
     - "3000:3000"

  customer:
    container_name: customer-service
    build:
      context: ./customer-service/
      dockerfile: Dockerfile
    links:
      [mongodb]

  product:
    container_name: product-service
    build:
      context: ./product-service/
      dockerfile: Dockerfile
    links:
      [mongodb]

  mongodb:
    image: mongo:latest
    container_name: mongo-database
    ports: 
      - "27017:27017"
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
      - mongoDbData:/data/db

volumes:
  mongoDbData: