version: '3'
services:
  
  node:
    image: micro-pig
    container_name: node-app-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "3000:3000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      transport.host: "127.0.0.1"